spring.application.name=backend_tdk

spring.datasource.url=jdbc:mysql://localhost:3306/data_tdk
spring.datasource.username=root
spring.datasource.password=Jeux@joneA56


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=9090

app.jwtSecret=MaSuperCleJWT123456789
app.jwtExpirationMs=86400000